import { DataRow } from './types';

export const tableData: DataRow[] = [
  {
    class: '3G',
    status: 'на уроке',
    percentLeft: 30,
    amountLeft: 5,
    quarantineStatus: 10,
  },
  {
    class: '32G',
    status: 'отсутствует',
    percentLeft: 50,
    amountLeft: 10,
    quarantineStatus: 6,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
  {
    class: '13G',
    status: 'на уроке',
    percentLeft: 0,
    amountLeft: 0,
    quarantineStatus: 0,
  },
];
