import { DataRow } from './DataRow';

export const tableData: DataRow[] = [
  {
    class: '3G',
    status: 'V',
    percentLeft: "30",
    amountLeft: "5",
    quarantineStatus: "10",
  },
  {
    class: '32G',
    status: 'X',
    percentLeft: "50",
    amountLeft: "10",
    quarantineStatus: "6",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'X',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'X',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'X',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'X',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'X',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'X',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
  {
    class: '13G',
    status: 'V',
    percentLeft: "0",
    amountLeft: "0",
    quarantineStatus: "0",
  },
];
